Set TLS verify
airbrake/airbrake-python pull request #102
Opened 2021-06-11 13:26 UTC by dtaniwaki

I set up Errbit in AWS and made the endpoint private for testing, then access the endpoint from EKS. I know we should always verify TLS, but as for especially testing, we should have an option to skip verification. Could you consider merging this feature?

2021-06-11 19:28 UTC, phumpal requested changes
Can you fix tests?

```
======================================================================
FAIL: test_deploy_payload (tests.test_notifier.TestAirbrakeNotifier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/airbrake-python/tests/test_notifier.py", line 340, in test_deploy_payload
    self.assertEqual(expected_call_args, requests_post.call_args)
AssertionError: call([268 chars]ication/json'}, params={'key': 'fake'}, timeout=5) != call([268 chars]ication/json'}, params={'key': 'fake'}, timeout=5, verify=None)
```

2021-06-12 06:32 UTC, dtaniwaki commented
@phumpal Thank you for your comment. I actually refactored the code and added some tests for the verify option. Would you review it again?

2021-06-16 05:36 UTC, phumpal commented on airbrake/notifier.py
> +            self._session.verify = os.environ["AIRBRAKE_CA_BUNDLE"]
Nice, thanks for adding these!

2021-06-16 05:37 UTC, phumpal commented on tests/test_notifier.py
> +    def test_default_verify(self):
Appreciate the additional tests :+1:

2021-06-16 05:37 UTC, phumpal commented on airbrake/notifier.py
> +        self._session = requests.Session()
It's understandable why we'd want to reuse the TCP connection but I'd expect to see an explanation in the commit message. Would you mind amending the commit explaining why a session object was added?

2021-06-16 05:37 UTC, phumpal requested changes
Just a few comments.

2021-06-16 09:56 UTC, dtaniwaki commented
@phumpal I updated the commit message. Would you check it? Please give me a sentence if the commit message is still not suitable.

2021-06-16 19:47 UTC, phumpal commented
@dtaniwaki perfect, thank you.  Rebase against master and I think we're good! Thanks for helping improve airbrake-python

2021-06-17 01:31 UTC, dtaniwaki commented
@phumpal I rebased the code, thanks!

2021-06-17 01:51 UTC, phumpal approved these changes

2021-06-17 01:59 UTC, merged